on: [push, pull_request]

name: Nightly

env:
  RUSTFLAGS: "-D warnings -A deprecated -A missing_abi"
  RUSTDOCFLAGS: "--cfg docsrs"
  RUSTTOOLCHAIN: "nightly"

jobs:
  quiche:
    runs-on: ubuntu-latest
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}

      - name: Run cargo test
        run: cargo test --verbose --all-targets --features=ffi,qlog

  fuzz:
    runs-on: ubuntu-latest
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Run cargo fuzz for packet_recv_client
        run: cargo fuzz run packet_recv_client -- -runs=1

      - name: Run cargo fuzz for packet_recv_server
        run: cargo fuzz run packet_recv_server -- -runs=1

      - name: Run cargo fuzz for qpack_decode
        run: cargo fuzz run qpack_decode -- -runs=1

  http3_test:
    runs-on: ubuntu-latest
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}

      - name: Run cargo test
        run: cargo test --no-run --verbose --manifest-path=tools/http3_test/Cargo.toml
