on: [push, pull_request]

name: Stable

env:
  RUSTFLAGS: "-D warnings -A deprecated -A missing_abi"
  RUSTTOOLCHAIN: "stable"

jobs:
  quiche:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tls-feature:
          - "" # default, boringssl-vendored
          - "boringssl-boring-crate"
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}

      - name: Run cargo test
        run: cargo test --verbose --all-targets --features=ffi,qlog,${{ matrix.tls-feature }}

  quiche_multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["aarch64-unknown-linux-gnu"]
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cross
        run: cargo-binstall -y cross

      - name: Run cargo test using cross
        run: cross test --target=${{ matrix.target }} --verbose --all-targets --features=ffi,qlog

  http3_test:
    runs-on: ubuntu-latest
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}

      - name: Run cargo test
        run: cargo test --no-run --verbose --manifest-path=tools/http3_test/Cargo.toml
